### ISSUE TITLE
Nome errado do repositório

### ISSUE THREAD

**Issue by pwebufersa** [Samuelaraujo10/pweb_2021.2_franciscoSamuel#1]
Prezado, o nome do repositório deve ser "pweb_2021.2_franciscoSamuel" e não "**_-_**pweb_2021.2_franciscoSamuel".

Vou esperar a correção.

**Comment by Samuelaraujo10** [comment]
Boa noite,

Consertei o dígito errado.

Em seg., 30 de jan. de 2023 às 16:07, Programação WEB - UFERSA Angicos <
***@***.***> escreveu:
